{% set conda_forge_name = "python-annoy" %}
{% set pypi_name = "annoy" %}
{% set version = "1.17.1" %}
{% set bundle_type = "tar.gz" %}
{% set sha256 = "bf177dbeafb81f63b2ac1e1246b1f26a2acc82e73ba46638734d29d8258122da" %}


package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle_type }}
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle_type }}
  sha256: {{ sha256 }}

build:
  number: 0


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - nose >=1.0
    - setuptools

  run:
    - python

test:
  imports:
    - annoy

about:
  home: https://github.com/spotify/annoy
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk.
  dev_url: https://github.com/spotify/annoy

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
