{% set conda_forge_name = "python-annoy" %}
{% set pypi_name = "annoy" %}
{% set version = "1.16.3" %}
{% set bundle_type = "tar.gz" %}
{% set sha256 = "fe2779664bd8846f2d67191a7e6010b8df890ac4586336748fd0697f31654379" %}


package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle_type }}
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle_type }}
  sha256: {{ sha256 }}

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - nose >=1.0
  run:
    - python

test:
  imports:
    - annoy

about:
  home: https://github.com/spotify/annoy
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk.'
  dev_url: https://github.com/spotify/annoy

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
