{% set conda_forge_name = "python-annoy" %}
{% set pypi_name = "annoy" %}
{% set version = "1.15.0" %}
{% set bundle_type = "tar.gz" %}
{% set sha256 = "0c490806bc4b6e731af5de90d1d099735d13f93cd7bc2977230967dc242ebf0f" %}


package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle_type }}
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle_type }}
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - nose >=1.0
  run:
    - python

test:
  imports:
    - annoy

about:
  home: https://github.com/spotify/annoy
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk.'
  dev_url: https://github.com/spotify/annoy

extra:
  recipe-maintainers:
    - pmlandwehr
