{% set conda_forge_name = "python-annoy" %}
{% set pypi_name = "annoy" %}
{% set version = "1.11.5" %}
{% set bundle_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "0b2196905954c3a8f47804f06e078602d66f3925526b13d20e117c52db6241ca" %}


package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle_type }}
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle_type }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [win]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - toolchain
    - nose >=1.0

  run:
    - python

test:
  imports:
    - annoy

about:
  home: https://github.com/spotify/annoy
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk.'
  dev_url: https://github.com/spotify/annoy

extra:
  recipe-maintainers:
    - pmlandwehr
