{% set conda_forge_name = "python-annoy" %}
{% set pypi_name = "annoy" %}
{% set version = "1.9.2" %}
{% set bundle_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "19802bbb4de6ad2d53ce8c90e82c4d61f25ea51ce04ac223289b6073c2f43ea1" %}
{% set build = 0 %}

package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.{{ bundle_type }}
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.{{ bundle_type }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [win]
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - nose >=1.0

  run:
    - python

test:
  imports:
    - annoy

about:
  home: https://github.com/spotify/annoy
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk.'
  dev_url: https://github.com/spotify/annoy

extra:
  recipe-maintainers:
    - pmlandwehr
