appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: GaHJptDWghaxesrE7B7POHfeR13/Lw3P0aqjQLsOogvEzIfMB/BJbAMm1k/mf6nFz3jyIC9uqw30GCKTnKTCVa37tMgaqhjiL8NGiQBSxDCvXyiRLxAy9ZtiiM7kkcig+78CcduK/JUD2lhe9gMnWnf2hBH1D0SJw5unnlghTNqRsHExWbhfmZhGyAEH1rYHAQ5O45Sjx5EdO2oWbT4dvhT+oFI8SkgGQlKCZejGKseBt9KaPO3CyvQXeOrQ8peYQu0w9XicPdULFCHcceq9jymqTXm4EITTsFit7RRaohicc+UJhHUgV9nbT3vqqfroicM7s8CnA/DjL4JvOWcQ6eJ/gSICIRZmyHLKn//8f4IfaIjfvsUG4yNdgyjF8fgNHbDEu6QhvVATBK8KG9e11b+n1DFClc5pI9ydwVvyUZ/C9ASG/ISFadQAr+oY8ABfHN/Ypbxm81K17oAhIVTe7h+LqDAzHC9h4SocwVLWVql1rcA3brXZMl7+A2/67W+wV+UVoYCY33swA/ugr+Buv1P6w+9tfGtB0WWh5617DGd5sIWQB+BsTmO+kFCOiSZDqeXetDh0460dOGNTp8iGlKmvWrmT12lmZ3lgTUoH9zNW45B+EeKzNshzsJpymi8xPCZiDK9Ap0Cn4A8Y3Dr+5g/gwxDSHMNrM2C7057OPgc=}
